FROM debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    apache2 \
    php \
    php-mysql \
    libapache2-mod-php \
    cron \
    curl \
    vim \
    python3 \
    python3-pip \
    net-tools \
    git \
    tmux \
    && apt clean

# Install Python dependencies
RUN apt install -y python3-requests && apt clean

# Enable Apache modules
RUN a2enmod rewrite

# Copy vhost configs
COPY vhost-site1.conf /etc/apache2/sites-available/site1.conf
COPY vhost-site2.conf /etc/apache2/sites-available/site2.conf

RUN a2dissite 000-default.conf && \
    a2ensite site1.conf site2.conf

# Add crontab if needed
COPY sites-cron /etc/cron.d/sites-cron
RUN chmod 0644 /etc/cron.d/sites-cron && crontab /etc/cron.d/sites-cron

# Copy the Python script
COPY apache_log_watcher.py /usr/local/bin/apache_log_watcher.py
RUN chmod +x /usr/local/bin/apache_log_watcher.py

# Add Listen ports
RUN echo "Listen 8036" >> /etc/apache2/ports.conf && \
    echo "Listen 8037" >> /etc/apache2/ports.conf

EXPOSE 8036 8037

CMD service cron start && apachectl -D FOREGROUND
